Repository OSOceanAcoustics/echopype, pull requests merged in 2021-11, with the labels that each got.

#475 add docs and docstring for sonar_model in open_raw
  docs/requirements.txt
  docs/source/convert.rst
  echopype/convert/api.py
Labels: docs

#476 EchoData.update_platform: use location_time instead of time2; clip location_time range to EchoData.beam["ping_time"]; created utils/coding.py to centralize encodings
  .pre-commit-config.yaml
  echopype/convert/set_groups_ad2cp.py
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/echodata/echodata.py
  echopype/tests/convert/test_convert.py
  echopype/tests/echodata/test_echodata.py
  echopype/utils/coding.py
Labels: Needs Complete Testing

#496 Add github citation file
  CITATION.cff
Labels: docs, enhancement
