Repository OSOceanAcoustics/echopype, pull requests merged in 2021-05, with the labels that each got.

#322 Remove download files code in convert test
  echopype/tests/test_convert.py
Labels: Need linting

#312 Add tests for preprocess functions
  .ci_helpers/run-test.py
  echopype/process/process_deprecated.py
  echopype/tests/test_preprocess.py
Labels: Need linting

#349 Update echodata to be able to read cloud data for zarr
  echopype/echodata/echodata.py
  echopype/tests/test_echodata.py
  echopype/utils/io.py
Labels: enhancement

#347 Fix docs in prep for v0.5 release
  docs/source/contributing.rst
  docs/source/convert.rst
  docs/source/index.rst
  docs/source/process.rst
  docs/source/whats-new.rst
Labels: docs

#337 Merge docs overhaul into master
  .gitignore
  .readthedocs.yml
  docs/requirements.txt
  docs/source/api.rst
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/convert.rst
  docs/source/data-format.rst
  docs/source/examples.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/open-converted.rst
  docs/source/process.rst
  docs/source/resources.rst
  docs/source/usage.rst
  docs/source/whats-new.rst
  docs/source/why.rst
  echopype/calibrate/__init__.py
  requirements-dev.txt
Labels: docs

#326 Add AD2CP parsing, remove redundant MODELS from convert (with commit history)
  .gitignore
  echopype/convert/__init__.py
  echopype/convert/api.py
  echopype/convert/convert.py
  echopype/convert/parse_ad2cp.py
  echopype/convert/set_groups_ad2cp.py
  echopype/convert/set_groups_base.py
  echopype/echodata/convention/1.0.yml
  echopype/tests/test_convert_ad2cp.py
Labels: Need linting

#361 Fix AD2CP Encoding Issues
  echopype/convert/api.py
  echopype/convert/set_groups_ad2cp.py
  echopype/convert/set_groups_base.py
  echopype/echodata/convention/1.0.yml
  echopype/tests/test_convert.py
  echopype/tests/test_convert_ad2cp.py
Labels: Need linting

#365 Update dependencies and add user conda environment file
  .ci_helpers/user_environment.yml
  requirements.txt
Labels: Needs Complete Testing

#366 Add ABC decorators to SetGroupsBase
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
Labels: Need linting

#370 Update check version and test env files
  .ci_helpers/check-version.py
  .ci_helpers/py3.7.yaml
  .ci_helpers/py3.8.yaml
  .ci_helpers/py3.9.yaml
  .github/workflows/ep-install.yaml
Labels: Needs Complete Testing
