Repository OSOceanAcoustics/echopype, pull requests merged in 2022-04, with the labels that each got.

#594 Add missing Sv and coordinate attributes for computed Sv and MVBS
  echopype/calibrate/api.py
  echopype/preprocess/api.py
Labels: data conversion, conventions

#619 Rename ek80 `quadrant` dimemsions and coordinates to `beam`
  echopype/calibrate/calibrate_ek.py
  echopype/convert/set_groups_ek80.py
  echopype/echodata/echodata.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/convert/test_convert_ek80.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/visualize/test_plot.py
  echopype/visualize/plot.py
Labels: conventions

#611 Implement DataTree for EchoData
  docs/source/open-converted.ipynb
  echopype/convert/api.py
  echopype/echodata/api.py
  echopype/echodata/convention/1.0.yml
  echopype/echodata/convention/utils.py
  echopype/echodata/echodata.py
  echopype/echodata/widgets/__init__.py
  echopype/echodata/widgets/static/css/style.css
  echopype/echodata/widgets/static/html/icons-svg-inline.html
  echopype/echodata/widgets/templates/echodata.html.j2
  echopype/echodata/widgets/templates/style.html.j2
  echopype/echodata/widgets/utils.py
  echopype/echodata/widgets/widgets.py
  echopype/tests/echodata/test_echodata.py
  echopype/utils/repr.py
  requirements.txt
Labels: Needs Complete Testing

#627 Update broken netcdf url in docs
  docs/source/why.rst
Labels: docs

#615 Add attributes for Sp and MVBS from index binning
  echopype/calibrate/__init__.py
  echopype/calibrate/api.py
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_base.py
  echopype/calibrate/calibrate_ek.py
  echopype/echodata/echodata.py
  echopype/preprocess/api.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/echodata/test_echodata.py
Labels: data conversion, conventions

#633 Update creating conda dev env instructions
  docs/source/contributing.rst
Labels: docs

#645 Small improvements re frequency selection in calibrate_ek
  echopype/calibrate/calibrate_ek.py
Labels: enhancement

#647 Rename Platform location_time and mru_time
  echopype/calibrate/calibrate_base.py
  echopype/convert/api.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/core.py
  echopype/echodata/combine.py
  echopype/echodata/convention/1.0.yml
  echopype/echodata/echodata.py
  echopype/qc/api.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/echodata/test_echodata_combine.py
  echopype/utils/coding.py
Labels: conventions

#651 Update setup-services.py to include images & volumes subtleties
  .ci_helpers/docker/docker-compose.yaml
  .ci_helpers/docker/setup-services.py
Labels: infrastructure
