Repository OSOceanAcoustics/echopype, pull requests merged in 2022-05, with the labels that each got.

#661 Add setitem method for echodata
  echopype/echodata/echodata.py
Labels: enhancement

#636 Add development roadmap to docs
  docs/source/_toc.yml
  docs/source/convert.rst
  docs/source/roadmap.md
Labels: docs

#621 Generalize echopype software provenance and apply to Sv and MVBS
  echopype/calibrate/api.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/echodata/combine.py
  echopype/preprocess/api.py
  echopype/preprocess/noise_est.py
  echopype/utils/prov.py
Labels: conventions

#657 Change the dimension `frequency` to `channel`
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_ek.py
  echopype/convert/parse_base.py
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/core.py
  echopype/echodata/combine.py
  echopype/echodata/convention/1.0.yml
  echopype/echodata/echodata.py
  echopype/preprocess/api.py
  echopype/preprocess/noise_est.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/convert/test_convert_azfp.py
  echopype/tests/convert/test_convert_ek60.py
  echopype/tests/convert/test_convert_ek80.py
  echopype/tests/preprocess/test_preprocess.py
  echopype/tests/visualize/test_plot.py
  echopype/visualize/api.py
  echopype/visualize/plot.py
Labels: conventions

#665 Add setattr functionality to echodata and more tests
  echopype/echodata/echodata.py
  echopype/tests/echodata/test_echodata.py
Labels: bug, enhancement

#674 Change src_filenames string attribute to source_filenames list-of-strings variable
  echopype/calibrate/api.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/echodata/combine.py
  echopype/preprocess/api.py
  echopype/tests/echodata/test_echodata.py
  echopype/utils/prov.py
Labels: conventions

#680 Modify variables that need `beam` and `ping_time` dims added to them for EK60
  echopype/convert/set_groups_ek60.py
Labels: conventions

#655 Add visualize doc and ignore ipynb for pre-commit
  .pre-commit-config.yaml
  docs/source/_static/ek500.png
  docs/source/_toc.yml
  docs/source/api.rst
  docs/source/viz.ipynb
  echopype/visualize/__init__.py
Labels: help wanted, docs

#687 Squeeze and drop the redundant `beam` dimension in calibration outputs
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_ek.py
  echopype/tests/calibrate/test_calibrate.py
Labels: computation

#696 Handle single pathlib Path in prov source_files_var
  echopype/utils/prov.py
Labels: bug, conventions

#698 Pinning CI s3fs version to latest
  .ci_helpers/py3.10.yaml
  .ci_helpers/py3.8.yaml
  .ci_helpers/py3.9.yaml
Labels: infrastructure

#697 Improve selection of calibration parameters from `Vendor` group
  echopype/calibrate/calibrate_ek.py
  echopype/tests/calibrate/test_calibrate.py
Labels: enhancement, computation

#703 Update contributors text [skip ci]
  README.md
  docs/source/_toc.yml
  docs/source/index.md
  docs/source/index.rst
Labels: docs

#689 Modify `combine_echodata` check for reversed time coordinates
  echopype/core.py
  echopype/echodata/combine.py
  echopype/tests/echodata/test_echodata_combine.py
Labels: enhancement

#660 Handle plotting of dimension frequency to channel
  echopype/tests/visualize/test_plot.py
  echopype/visualize/api.py
  echopype/visualize/plot.py
Labels: enhancement

#688 Development roadmap in docs
  docs/source/_config.yml
  docs/source/_toc.yml
  docs/source/roadmap.md
Labels: docs

#635 Restructure data format section in docs
  docs/source/_static/echodata_sample_v0.5.x.html
  docs/source/_toc.yml
  docs/source/convert.rst
  docs/source/data-format-5to6.ipynb
  docs/source/data-format-processed.ipynb
  docs/source/data-format-raw.ipynb
  docs/source/data-format.md
  docs/source/data-format.rst
  docs/source/open-converted.ipynb
  docs/source/whats-new.rst
  docs/source/why.rst
Labels: docs

#641 Add v0.6.0 release notes
  docs/source/data-format-5to6.ipynb
  docs/source/whats-new.md
Labels: docs
