Repository OSOceanAcoustics/echopype, pull requests merged in 2022-09, with the labels that each got.

#804 Fix version string on CI
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
Labels: infrastructure

#805 Update CI to use micromamba
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
Labels: infrastructure

#807 chore: Rename ci.yaml to build.yaml to be more clear
  .github/workflows/build.yaml
  README.md
Labels: infrastructure

#813 Add dependabot yml for updating github actions
  .github/dependabot.yml
Labels: infrastructure

#818 Order the `channel` coordinate values
  echopype/convert/parse_azfp.py
  echopype/convert/parsed_to_zarr_ek60.py
  echopype/convert/parsed_to_zarr_ek80.py
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
Labels: enhancement

#820 🐛 Delete 'v' in version string for really old version to avoid error
  echopype/echodata/echodata.py
Labels: bug

#814 Handle xml_path in EchoData provenance on open_raw and combine_echodata
  echopype/calibrate/api.py
  echopype/convert/api.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/echodata/combine.py
  echopype/utils/prov.py
Labels: enhancement

#808 Address memory issues in `combine`
  echopype/convert/api.py
  echopype/convert/set_groups_ek60.py
  echopype/echodata/combine.py
  echopype/echodata/zarr_combine.py
  echopype/qc/api.py
  echopype/tests/echodata/test_echodata_combine.py
  echopype/utils/coding.py
  echopype/utils/io.py
Labels: enhancement
