Repository OSOceanAcoustics/echopype, pull requests merged in 2022-12, with the labels that each got.

#855 Add default consolidated flag for to_zarr
  echopype/convert/api.py
  echopype/echodata/combine.py
  echopype/echodata/echodata.py
  echopype/echodata/zarr_combine.py
  echopype/qc/api.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/echodata/test_echodata_combine.py
  echopype/tests/echodata/test_zarr_combine.py
  echopype/tests/echodata/utils.py
  echopype/utils/io.py
Labels: enhancement

#892 Implement subset portion of `channel_selection` input for `combine_echodata`
  echopype/echodata/combine.py
  echopype/echodata/zarr_combine.py
  echopype/tests/echodata/test_echodata_combine.py
  echopype/tests/echodata/test_zarr_combine.py
Labels: enhancement, tests

#908 Fix meta_source_filenames bug and enable (meta)source_filenames appending of path and list
  echopype/tests/utils/test_source_filenames.py
  echopype/utils/prov.py
Labels: bug, enhancement

#902 Initialize testing framework setup
  echopype/testing.py
  echopype/tests/README.md
  echopype/tests/calibrate/__init__.py
  echopype/tests/conftest.py
  echopype/tests/consolidate/__init__.py
  echopype/tests/convert/__init__.py
  echopype/tests/convert/test_convert_source_target_locs.py
  echopype/tests/echodata/__init__.py
  echopype/tests/echodata/conftest.py
  echopype/tests/echodata/test_api_integration.py
  echopype/tests/echodata/test_combine_integration.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/echodata/test_echodata_integration.py
  echopype/tests/echodata/test_echodata_misc.py
  echopype/tests/echodata/test_echodata_structure.py
  echopype/tests/echodata/test_zarr_combine.py
  echopype/tests/echodata/utils.py
  echopype/tests/metrics/__init__.py
  echopype/tests/preprocess/__init__.py
  echopype/tests/utils/__init__.py
  echopype/tests/visualize/__init__.py
Labels: tests

#918 Add dataset and variable-level provenance to new mask and add_splitbeam_angle functions
  echopype/consolidate/api.py
  echopype/mask/api.py
  echopype/utils/prov.py
Labels: enhancement

#904 Refactor calibrate subpackage
  echopype/calibrate/api.py
  echopype/calibrate/cal_params.py
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_base.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ek80_complex.py
  echopype/calibrate/env_params.py
  echopype/calibrate/env_params_old.py
  echopype/calibrate/range.py
  echopype/echodata/echodata.py
  echopype/echodata/simrad.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/consolidate/test_consolidate.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/echodata/test_echodata_simrad.py
Labels: enhancement
