Repository OSOceanAcoustics/echopype, pull requests merged in 2022-08, with the labels that each got.

#749 Add function to interpolate location to calibrated dataset
  echopype/__init__.py
  echopype/consolidate/__init__.py
  echopype/consolidate/api.py
  echopype/tests/consolidate/test_consolidate.py
Labels: computation

#762 Overhaul access pattern [all tests ci]
  echopype/calibrate/api.py
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/env_params.py
  echopype/convert/api.py
  echopype/echodata/combine.py
  echopype/echodata/echodata.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/convert/test_convert_azfp.py
  echopype/tests/convert/test_convert_ek60.py
  echopype/tests/convert/test_convert_ek80.py
  echopype/tests/convert/test_convert_source_target_locs.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/echodata/test_echodata_combine.py
  echopype/tests/preprocess/test_preprocess.py
  echopype/tests/visualize/test_plot.py
  echopype/visualize/api.py
Labels: ready for review

#772 Add logging and optional printouts
  echopype/__init__.py
  echopype/calibrate/api.py
  echopype/calibrate/calibrate_ek.py
  echopype/convert/api.py
  echopype/convert/parse_azfp.py
  echopype/convert/parse_base.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/convert/utils/ek_raw_io.py
  echopype/convert/utils/ek_raw_parsers.py
  echopype/echodata/combine.py
  echopype/echodata/echodata.py
  echopype/echodata/sensor_ep_version_mapping/v05x_to_v06x.py
  echopype/tests/utils/test_utils_log.py
  echopype/tests/visualize/test_plot.py
  echopype/utils/io.py
  echopype/utils/log.py
  echopype/visualize/api.py
  echopype/visualize/plot.py
Labels: enhancement, ready for review

#774 Add functionality that directly writes variables to a temporary zarr store
  echopype/convert/api.py
  echopype/convert/parse_ad2cp.py
  echopype/convert/parse_azfp.py
  echopype/convert/parse_base.py
  echopype/convert/parse_ek60.py
  echopype/convert/parse_ek80.py
  echopype/convert/parsed_to_zarr.py
  echopype/convert/parsed_to_zarr_ek60.py
  echopype/convert/parsed_to_zarr_ek80.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/core.py
  echopype/echodata/api.py
  echopype/echodata/echodata.py
  echopype/tests/convert/test_parsed_to_zarr.py
  requirements.txt
Labels: ready for review

#780 Modify `set_beam()` so it returns a list
  echopype/convert/api.py
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_ek60.py
Labels: ready for review

#738 Add `depth` as an additional variable in Sv dataset
  echopype/consolidate/__init__.py
  echopype/consolidate/api.py
  echopype/preprocess/__init__.py
  echopype/preprocess/api.py
  echopype/tests/consolidate/test_consolidate.py
  echopype/tests/preprocess/test_api.py
Labels: computation

#784 Add attention statement in docs for `open_raw` beta feature
  docs/source/api.rst
  docs/source/convert.rst
Labels: docs

#794 `open_raw(offload_to_zarr=True)` integration tests and bug fix
  echopype/convert/parsed_to_zarr_ek60.py
  echopype/convert/parsed_to_zarr_ek80.py
  echopype/tests/convert/test_parsed_to_zarr.py
Labels: bug, tests

#797 Clean up `combine_echodata`
  echopype/echodata/combine.py
  echopype/qc/api.py
Labels: enhancement
