Repository OSOceanAcoustics/echopype, pull requests merged in 2022-03, with the labels that each got.

#565 Consolidate convention specs into single yml file pre loaded via import
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/echodata/__init__.py
  echopype/echodata/convention/1.0.yml
  echopype/echodata/convention/__init__.py
  echopype/echodata/convention/attrs.py
  echopype/echodata/convention/conv.py
  echopype/echodata/echodata.py
  echopype/utils/uwa.py
Labels: conventions

#574 Move Beam group to Sonar/Beam_group1 and Beam_power to Sonar/Beam_power
  echopype/convert/add_ancillary.py
  echopype/convert/api.py
  echopype/convert/convert_combine.py
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/echodata/convention/1.0.yml
  echopype/echodata/echodata.py
  echopype/tests/convert/test_convert_azfp.py
  echopype/tests/convert/test_convert_ek80.py
  echopype/tests/convert/test_convert_source_target_locs.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/old/test_old.py
Labels: conventions

#510 Add parser for Echoview ECS file
  echopype/calibrate/ecs_parser.py
  echopype/tests/calibrate/test_ecs.py
Labels: enhancement

#590 Change range to echo_range
  docs/source/process.rst
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_base.py
  echopype/calibrate/calibrate_ek.py
  echopype/echodata/echodata.py
  echopype/metrics/summary_statistics.py
  echopype/preprocess/api.py
  echopype/preprocess/noise_est.py
  echopype/process/process_deprecated.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/metrics/test_metrics_summary_statistics.py
  echopype/tests/old/test_old.py
  echopype/tests/preprocess/test_preprocess.py
  echopype/tests/visualize/test_plot.py
  echopype/visualize/api.py
  echopype/visualize/plot.py
Labels: conventions

#601 Remove old API (those prior to v0.5.0)
  .ci_helpers/run-test.py
  .coveragerc
  .pre-commit-config.yaml
  MANIFEST.in
  docs/source/convert.rst
  docs/source/data-format.rst
  docs/source/process.rst
  echopype/__init__.py
  echopype/convert/__init__.py
  echopype/convert/api.py
  echopype/convert/convert.py
  echopype/convert/convert_combine.py
  echopype/echodata/echodata.py
  echopype/process/__init__.py
  echopype/process/process_deprecated.py
  echopype/tests/convert/test_convert_azfp.py
  echopype/tests/convert/test_convert_ek80.py
  echopype/tests/old/test_old.py
Labels: design

#604 Upgrade python minimum to 3.8 and tidy up packaging
  .ci_helpers/docker/setup-services.py
  .ci_helpers/py3.10.yaml
  .ci_helpers/py3.7.yaml
  .ci_helpers/py3.8.yaml
  .ci_helpers/py3.9.yaml
  .ci_helpers/run-test.py
  .flake8
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  .readthedocs.yml
  docs/source/contributing.rst
  echopype/calibrate/api.py
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_base.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ecs_parser.py
  echopype/convert/api.py
  echopype/convert/parse_ad2cp.py
  echopype/convert/parse_azfp.py
  echopype/convert/parse_base.py
  echopype/convert/set_groups_ad2cp.py
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/convert/utils/ek_date_conversion.py
  echopype/convert/utils/ek_raw_io.py
  echopype/convert/utils/ek_raw_parsers.py
  echopype/echodata/combine.py
  echopype/echodata/convention/conv.py
  echopype/echodata/echodata.py
  echopype/metrics/summary_statistics.py
  echopype/preprocess/api.py
  echopype/qc/api.py
  echopype/utils/io.py
  echopype/utils/repr.py
  echopype/utils/uwa.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  setup.cfg
  setup.py
Labels: Needs Complete Testing
