Repository OSOceanAcoustics/echopype, pull requests merged in 2022-07, with the labels that each got.

#736 Fix regression bug in computing MVBS in selecting `echo_range` for specific frequency
  echopype/calibrate/calibrate_azfp.py
  echopype/preprocess/api.py
Labels: bug, computation

#748 Update datatree to v0.0.6 [all tests ci]
  echopype/convert/api.py
  echopype/echodata/combine.py
  echopype/echodata/echodata.py
  echopype/echodata/sensor_ep_version_mapping/v05x_to_v06x.py
  echopype/echodata/widgets/templates/echodata.html.j2
  echopype/echodata/widgets/utils.py
  requirements.txt
Labels: enhancement

#751 Add v0.6.1 release note
  docs/source/whats-new.md
Labels: docs

#759 Add calibrator mappings for ES70, ES80, EA640
  docs/source/whats-new.md
  echopype/calibrate/api.py
  echopype/echodata/echodata.py
Labels: bug

#761 Docker fixes [all tests ci]
  .ci_helpers/docker/setup-services.py
  .github/workflows/ci.yaml
  .github/workflows/pr.yaml
  echopype/tests/conftest.py
Labels: infrastructure

#764 Updates to "Contributing to echopype" doc page [skip ci]
  docs/source/contributing.rst
Labels: docs
