Repository OSOceanAcoustics/echopype, pull requests merged in 2022-06, with the labels that each got.

#505 Refactor AD2CP to improve speed and memory usage through removal of xr.merge
  echopype/convert/parse_ad2cp.py
  echopype/convert/set_groups_ad2cp.py
Labels: enhancement

#717 Add sphinx-panels to docs/requirements.txt
  docs/requirements.txt
Labels: bug, docs

#721 Update pr action to use title [all tests ci]
  .github/workflows/pr.yaml
Labels: infrastructure

#731 AD2CP Data Format Reorganization
  echopype/convert/ad2cp_fields.yaml
  echopype/convert/api.py
  echopype/convert/parse_ad2cp.py
  echopype/convert/set_groups_ad2cp.py
  echopype/echodata/convention/1.0.yml
  echopype/tests/convert/test_convert_ad2cp.py
  echopype/utils/coding.py
Labels: conventions

#718 Use `mode` to determine whether to save angle data for EK60
  echopype/convert/set_groups_ek60.py
  echopype/test_data/README.md
  echopype/tests/convert/test_convert_ek60.py
Labels: data conversion

#724 Check filter coeffs existence in `SetGroupsEK80.set_vendor`
  echopype/convert/set_groups_ek80.py
  echopype/test_data/README.md
  echopype/tests/convert/test_convert_ek80.py
Labels: data conversion

#744 Fix python version requirements in docs
  docs/requirements.txt
  docs/source/installation.rst
Labels: docs

#735 Function to use `frequency_nominal` in place of `channel` for dimension/coordinate
  echopype/__init__.py
  echopype/tests/utils/test_utils_common.py
  echopype/utils/__init__.py
  echopype/utils/common.py
Labels: computation

#746 Add windows build CI [skip ci]
  .github/workflows/windows.yaml
Labels: infrastructure
