Repository OSOceanAcoustics/echopype, pull requests merged in 2023-07, with the labels that each got.

#1071 Remove `ui_param`
  echopype/convert/set_groups_ad2cp.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek80.py
Labels: data conversion

#1067 Handling problematic NMEA messages when setting lat/lon in Platform group
  echopype/convert/set_groups_base.py
Labels: data conversion

#1075 Move some Vendor-specific group attributes to data variables
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_ek80.py
Labels: data conversion

#1065 Revise qc function to clean up reversed time
  .ci_helpers/run-test.py
  echopype/qc/api.py
  echopype/tests/qc/test_qc.py
Labels: enhancement

#1082 Remove deprecated preprocess subpackage [all tests ci]
  docs/source/api.rst
  docs/source/process.rst
  echopype/__init__.py
  echopype/preprocess/__init__.py
  echopype/preprocess/api.py
Labels: design

#1056 Drop beam dimension
  echopype/calibrate/cal_params.py
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/range.py
  echopype/consolidate/split_beam_angle.py
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/tests/calibrate/test_cal_params.py
  echopype/tests/calibrate/test_cal_params_integration.py
  echopype/tests/calibrate/test_ecs_integration.py
  echopype/tests/convert/test_convert_azfp.py
  echopype/tests/convert/test_convert_ek60.py
  echopype/tests/convert/test_convert_ek80.py
  echopype/tests/echodata/test_echodata.py
Labels: conventions

#1084 Add `mamba` recommendation into docs
  docs/source/contributing.rst
  docs/source/installation.rst
Labels: docs

#1094 Add missing EK80 Beam_group variables
  docs/source/process.rst
  echopype/convert/set_groups_ek80.py
Labels: enhancement

#1099 Update a couple of "extra" EK60 Beam_group1 variables
  echopype/convert/set_groups_ek60.py
  echopype/utils/coding.py
Labels: enhancement

#1104 Rename `fs_receiver` in Vendor-specific group
  echopype/calibrate/cal_params.py
  echopype/convert/set_groups_ek80.py
Labels: bug

#1101 EK60, add mandatory `transmit_type` as a scalar
  echopype/convert/set_groups_ek60.py
Labels: conventions
