Repository OSOceanAcoustics/echopype, pull requests merged in 2023-04, with the labels that each got.

#1023 Correct or add missing SONAR-netCDF4 variable attributes for AZFP
  echopype/convert/set_groups_azfp.py
Labels: bug, conventions

#1019 Impedance type change, name change, bug fix
  echopype/calibrate/cal_params.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ek80_complex.py
  echopype/convert/set_groups_ek80.py
  echopype/convert/utils/ek_raw_parsers.py
  echopype/tests/calibrate/test_cal_params.py
  echopype/tests/calibrate/test_calibrate_ek80.py
  echopype/tests/calibrate/test_ecs_integration.py
Labels: bug, conventions

#1024 Refactor AZFP parser code
  echopype/convert/parse_azfp.py
Labels: design

#1037 Remove unneeded (mistaken) object return in processing level decorator function
  echopype/utils/prov.py
Labels: bug
