Repository OSOceanAcoustics/echopype, pull requests merged in 2023-08, with the labels that each got.

#1107 Change 2 AZFP `Beam_group1` data types & add `long_name` to Vendor attributes
  echopype/convert/set_groups_azfp.py
Labels: conventions

#1103 Add missing, mandatory `Beam_groupX` variables
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/utils/coding.py
Labels: conventions

#1113 Add new Provenance `combination_*` attributes with `combine_echodata`
  echopype/echodata/combine.py
  echopype/echodata/echodata.py
  echopype/tests/echodata/test_echodata_combine.py
  echopype/utils/prov.py
Labels: enhancement, conventions

#1102 AZFP: add missing mandatory Beam_group1 variables
  echopype/convert/set_groups_azfp.py
Labels: conventions

#1091 Standardize use of `transmit_frequency_start/stop` and use `pulse_form` for BB checks
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ek80_complex.py
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/echodata/convention/1.0.yml
  echopype/echodata/simrad.py
  echopype/tests/calibrate/test_cal_params_integration.py
  echopype/tests/calibrate/test_ecs_integration.py
Labels: conventions

#1114 Add missing sampling_offset_time for EK60 & set EK60/80 beam_direction_x/y/z to nan as needed
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
Labels: enhancement, conventions

#1116 fix: update prov attributes combine
  echopype/echodata/combine.py
  echopype/tests/echodata/test_echodata_combine.py
Labels: bug

#1105 Small fixes for BB and splitbeam angle handling
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ek80_complex.py
  echopype/consolidate/api.py
  echopype/consolidate/split_beam_angle.py
  echopype/tests/calibrate/test_calibrate_ek80.py
  echopype/tests/calibrate/test_ek80_complex.py
Labels: bug

#1089 Update EchoData examples in docs
  docs/source/data-format-raw.ipynb
Labels: docs

#1093 Documentation updates: data processing sections
  docs/source/_config.yml
  docs/source/_toc.yml
  docs/source/api.rst
  docs/source/data-format-processed.ipynb
  docs/source/data-format-raw.ipynb
  docs/source/data-format-sonarnetcdf4.ipynb
  docs/source/data-format.md
  docs/source/data-proc-additional.ipynb
  docs/source/data-proc-func.ipynb
  docs/source/data-proc.md
  docs/source/images/beam_dim_v5-01.png
  docs/source/images/echo_range.png
  docs/source/references.bib
  echopype/__init__.py
  echopype/consolidate/api.py
  echopype/metrics/__init__.py
Labels: docs

#1132 Fixes / changes to docs in "Data processing" pages
  docs/source/data-proc-additional.ipynb
  docs/source/data-proc-func.ipynb
  docs/source/data-proc.md
  docs/source/images/beam_dim_v5-01.png
Labels: docs

#1133 Add discussion on z-axis vertical coordinate system and variables
  docs/source/data-proc-additional.ipynb
  docs/source/images/z_axis_vars_v3.png
Labels: docs

#1134 Updates to Raw data format pages
  docs/source/_toc.yml
  docs/source/data-format-5to6.ipynb
  docs/source/data-format-changes.ipynb
  docs/source/data-format-sonarnetcdf4.ipynb
  docs/source/data-format.md
  docs/source/process.rst
  docs/source/processing-levels.md
Labels: docs

#1137 Fix inline `cite` problem and add bibliography page
  docs/source/_config.yml
  docs/source/_toc.yml
  docs/source/data-proc-func.ipynb
  docs/source/references.bib
  docs/source/zbibliography.md
Labels: docs

#1063 Draft v0.8.0 release notes
  docs/source/whats-new.md
Labels: docs

#1143 Remove automatic version conversion in `open_converted`
  docs/source/data-format-changes.ipynb
  echopype/echodata/echodata.py
  echopype/tests/echodata/test_echodata_version_convert.py
Labels: bug

#1106 Improved input syntax for `frequency_differencing` operation
  echopype/mask/api.py
  echopype/mask/freq_diff.py
  echopype/tests/mask/test_mask.py
  echopype/tests/utils/test_processinglevels_integration.py
Labels: enhancement
