Repository OSOceanAcoustics/echopype, pull requests merged in 2023-11, with the labels that each got.

#1196 Enhanced `update_platform` to Auto-assign first `ping_time` as `Platform` timestamp for fixed-location update case without timestamp. [all tests ci]
  echopype/echodata/echodata.py
  echopype/tests/echodata/test_echodata.py
Labels: enhancement

#1207 Added `depth_from_pressure` method required for the calculation of `vertical_offset` value
  echopype/tests/utils/test_utils_misc.py
  echopype/utils/misc.py
Labels: enhancement, conventions

#1167 fix(commongrid): fix bugs and improve `compute_NASC` using flox
  echopype/commongrid/__init__.py
  echopype/commongrid/api.py
  echopype/commongrid/mvbs.py
  echopype/commongrid/nasc.py
  echopype/commongrid/utils.py
  echopype/tests/commongrid/conftest.py
  echopype/tests/commongrid/test_api.py
  echopype/tests/commongrid/test_mvbs.py
  echopype/tests/commongrid/test_nasc.py
Labels: bug, enhancement

#1214 Removed the unused `ALL` param in parser object.
  echopype/convert/api.py
  echopype/convert/parse_ad2cp.py
  echopype/convert/parse_azfp.py
  echopype/convert/parse_base.py
  echopype/convert/parse_ek60.py
  echopype/convert/parse_ek80.py
  echopype/tests/convert/test_parse_base.py
Labels: enhancement

#1209 Refactored `EchoData.update_platform` to improve readability
  echopype/echodata/echodata.py
  echopype/echodata/utils_platform.py
Labels: enhancement

#1218 Moved `complex` data type reshaping to parser rather than during rectangularize [all tests ci]
  echopype/convert/parse_base.py
  echopype/convert/set_groups_ek80.py
  echopype/convert/utils/ek_raw_parsers.py
Labels: enhancement, Needs Complete Testing

#1215 Fixes `UnicodeDecodeError` for ES60 files [all tests ci]
  echopype/convert/utils/ek_raw_parsers.py
Labels: bug

#1219 Handle missing `receiver_sampling_frequency` in EK80 data [all tests ci]
  echopype/calibrate/cal_params.py
Labels: bug

#1228 Fixes build issue with `minioci.dockerfile` [all tests ci]
  .ci_helpers/docker/minioci.dockerfile
Labels: bug

#1233 Add test for ES60 spare field decoding issue
  echopype/tests/conftest.py
  echopype/tests/convert/test_convert_ek60.py
Labels: tests
