Repository OSOceanAcoustics/echopype, pull requests merged in 2023-10, with the labels that each got.

#1182 added support for AZFP multiple phase attributes parsing
  echopype/convert/parse_azfp.py
  echopype/convert/set_groups_azfp.py
  echopype/tests/convert/test_convert_azfp.py
Labels: enhancement, data conversion

#1192 ci: Update CI to barebone python [all tests ci]
  .github/workflows/build.yaml
  .github/workflows/pr.yaml
  echopype/tests/convert/test_parsed_to_zarr.py
Labels: infrastructure, dependencies

#1189 `parse_azfp` now parses AZFP pressure data according to given matlab code
  echopype/convert/parse_azfp.py
  echopype/convert/set_groups_azfp.py
  echopype/tests/convert/test_convert_azfp.py
Labels: enhancement
