Repository OSOceanAcoustics/echopype, pull requests merged in 2023-03, with the labels that each got.

#944 Improving pulse compressed Sv computation and echo range computation
  echopype/calibrate/cal_params.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ecs_parser.py
  echopype/calibrate/ek80_complex.py
  echopype/calibrate/env_params.py
  echopype/calibrate/range.py
  echopype/convert/set_groups_ek80.py
  echopype/echodata/simrad.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/calibrate/test_calibrate_ek80.py
  echopype/tests/conftest.py
  echopype/utils/uwa.py
Labels: computation

#952 Revise `env_params` related routines in calibration
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/env_params.py
  echopype/calibrate/range.py
  echopype/echodata/echodata.py
  echopype/tests/calibrate/test_env_params.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/visualize/test_plot.py
  echopype/visualize/api.py
Labels: enhancement, computation

#947 Fix windows github actions workflow
  .github/workflows/windows-utils.yaml
Labels: infrastructure

#962 Update the name of `offload_to_zarr` to `use_swap` and `max_zarr_mb` to `max_mb`
  docs/source/convert.rst
  echopype/convert/api.py
  echopype/tests/convert/test_parsed_to_zarr.py
Labels: enhancement

#927 Update CITATION.cff
  CITATION.cff
  docs/source/index.md
Labels: docs

#954 Update software behavior to use the default echopype home directory
  .ci_helpers/run-test.py
  .gitignore
  docs/source/convert.rst
  docs/source/open-converted.ipynb
  echopype/__init__.py
  echopype/convert/api.py
  echopype/convert/parsed_to_zarr.py
  echopype/core.py
  echopype/echodata/combine.py
  echopype/tests/echodata/test_echodata_combine.py
  echopype/tests/echodata/test_zarr_combine.py
  echopype/tests/test_core.py
  echopype/tests/utils/test_utils_io.py
  echopype/utils/io.py
Labels: enhancement

#955 Allow passing in `cal_params` for calibration
  echopype/calibrate/cal_params.py
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_base.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/env_params.py
  echopype/tests/calibrate/test_cal_params.py
  echopype/tests/calibrate/test_cal_params_integration.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/calibrate/test_calibrate_ek80.py
Labels: enhancement, computation

#968 Unify `echo_range` order of dimensions across sonar models
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/range.py
  echopype/tests/calibrate/test_range_integration.py
Labels: enhancement

#971 Refactor split-beam processing and add BB with pc option
  echopype/calibrate/cal_params.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ek80_complex.py
  echopype/consolidate/api.py
  echopype/consolidate/split_beam_angle.py
  echopype/tests/calibrate/test_cal_params.py
  echopype/tests/calibrate/test_calibrate_ek80.py
  echopype/tests/consolidate/test_consolidate_integration.py
Labels: computation

#970 Fix `combine_echodata` b/w combined and single echodata object.
  echopype/echodata/zarr_combine.py
  echopype/tests/echodata/test_zarr_combine.py
Labels: bug

#974 Add v0.6.4 release notes
  docs/source/whats-new.md
Labels: docs

#986 Handling of non-positive values causing log10 warnings on EK calibration
  echopype/calibrate/calibrate_ek.py
Labels: bug

#989 Add what's new for v0.6.4.1
  docs/source/whats-new.md
Labels: docs

#994 Add test for splitbeam angle ek80_CW_power case
  echopype/tests/consolidate/test_consolidate_integration.py
Labels: tests

#992 Standardize use of sonar metadata as `Sonar` global attributes vs (for EK80 only) variables
  echopype/convert/set_groups_azfp.py
  echopype/convert/set_groups_ek80.py
Labels: conventions

#985 Ensure `env_params` intake for calibration
  echopype/calibrate/cal_params.py
  echopype/calibrate/calibrate_azfp.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/env_params.py
  echopype/calibrate/range.py
  echopype/consolidate/api.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/calibrate/test_calibrate_ek80.py
  echopype/tests/calibrate/test_env_params.py
  echopype/tests/calibrate/test_env_params_integration.py
  echopype/tests/consolidate/test_consolidate_integration.py
  echopype/tests/preprocess/test_preprocess.py
  echopype/tests/visualize/test_plot.py
Labels: enhancement

#993 Move `preprocess` functions and tests new `clean` and `commongrid` subpackages
  .ci_helpers/run-test.py
  echopype/__init__.py
  echopype/clean/__init__.py
  echopype/clean/api.py
  echopype/clean/noise_est.py
  echopype/commongrid/__init__.py
  echopype/commongrid/api.py
  echopype/commongrid/mvbs.py
  echopype/consolidate/api.py
  echopype/preprocess/__init__.py
  echopype/preprocess/api.py
  echopype/tests/clean/test_noise.py
  echopype/tests/commongrid/test_mvbs.py
  echopype/tests/consolidate/test_consolidate_integration.py
  echopype/tests/visualize/test_plot.py
Labels: design

#1000 Add more add_location tests and weak add_location
  echopype/consolidate/api.py
  echopype/tests/consolidate/test_consolidate_integration.py
Labels: tests

#1004 Fix test failure due to `ecs_file` requirement
  echopype/tests/echodata/test_echodata.py
  echopype/tests/visualize/test_plot.py
  echopype/visualize/api.py
Labels: Needs Complete Testing

#1005 Add `compute_NASC`
  echopype/commongrid/__init__.py
  echopype/commongrid/api.py
  echopype/commongrid/nasc.py
  echopype/tests/commongrid/test_nasc.py
  requirements.txt
Labels: computation

#1008 Draft docs page for processing levels and updated processing_level_url
  docs/source/_toc.yml
  docs/source/processing-levels.md
  echopype/utils/prov.py
Labels: docs, product levels
