Repository OSOceanAcoustics/echopype, pull requests merged in 2024-06, with the labels that each got.

#1311 Support lazy-loaded EK80 broadband-complex data
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ek80_complex.py
  echopype/tests/calibrate/test_calibrate_ek80.py
Labels: enhancement

#1336 Remove the `visualize` subpackage
  echopype/colormap/__init__.py
  echopype/colormap/cm.py
  echopype/tests/colormap/test_colormap.py
  echopype/tests/visualize/test_plot.py
  echopype/visualize/__init__.py
  echopype/visualize/api.py
  echopype/visualize/plot.py
Labels: infrastructure

#1318 Add `.bot` and `.idx` files to EK60/EK80 parsing
  echopype/convert/api.py
  echopype/convert/parse_ad2cp.py
  echopype/convert/parse_azfp.py
  echopype/convert/parse_base.py
  echopype/convert/parse_ek60.py
  echopype/convert/parse_ek80.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek60.py
  echopype/convert/set_groups_ek80.py
  echopype/convert/utils/ek_raw_io.py
  echopype/convert/utils/ek_raw_parsers.py
  echopype/core.py
  echopype/tests/convert/test_convert_ek.py
  echopype/tests/convert/test_convert_ek80.py
  echopype/tests/convert/test_parse_base.py
  requirements.txt
Labels: feature request

#1347 Update docs for visualization
  docs/source/references.bib
  docs/source/viz.ipynb
Labels: docs

#1345 Allow `MVBS` into `ep.mask.apply_mask`, and add Alignment Check for Target Variable and Mask
  echopype/mask/api.py
  echopype/mask/freq_diff.py
  echopype/tests/mask/test_mask.py
Labels: bug, enhancement

#1337 Fix Duck Array `RuntimeWarning` for EK60 `ep.open_raw`
  echopype/tests/convert/test_convert_ek60.py
  echopype/utils/coding.py
Labels: bug
