Repository OSOceanAcoustics/echopype, pull requests merged in 2024-04, with the labels that each got.

#1230 Apply Mask Changes: Multichannel, Allow Depth, Simplify Fill Value
  echopype/mask/api.py
  echopype/tests/mask/test_mask.py
Labels: enhancement, processing functions

#1297 One time `dev` merge to `main`
  echopype/calibrate/cal_params.py
  echopype/calibrate/ek80_complex.py
  echopype/calibrate/env_params.py
  echopype/mask/api.py
  echopype/tests/calibrate/test_cal_params.py
  echopype/tests/calibrate/test_calibrate_ek80.py
  echopype/tests/calibrate/test_env_params.py
  echopype/tests/mask/test_mask.py
Labels: infrastructure

#1296 Add warnings and raised errors for `add_location`
  echopype/consolidate/api.py
  echopype/tests/consolidate/test_consolidate_integration.py
Labels: bug, enhancement

#1299 Fix time encoding to use int64 and "nanoseconds since 1970-01-01 00:00:00Z"
  echopype/convert/set_groups_base.py
  echopype/tests/utils/test_coding.py
  echopype/utils/coding.py
Labels: bug

#1304 Update `_calc_Sv_offset` for AZFP parsing
  echopype/convert/parse_azfp.py
  echopype/tests/convert/test_convert_azfp.py
Labels: data conversion

#1307 Move Compute Sv Offset inside of AZFP Parser
  echopype/convert/parse_azfp.py
  echopype/convert/set_groups_azfp.py
Labels: enhancement

#1269 expose func arg and skip_na to compute_MVBS users
  echopype/commongrid/api.py
  echopype/commongrid/utils.py
  echopype/echodata/echodata.py
  echopype/tests/commongrid/conftest.py
  echopype/tests/commongrid/test_commongrid_api.py
Labels: enhancement, feature request

#1302 Support for EK80 Broadband Complex Multiplex Data
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ek80_complex.py
  echopype/calibrate/env_params.py
  echopype/tests/calibrate/test_calibrate_ek80.py
  echopype/tests/calibrate/test_ek80_complex.py
  echopype/tests/calibrate/test_env_params.py
Labels: bug, feature request
