Repository OSOceanAcoustics/echopype, pull requests merged in 2024-07, with the labels that each got.

#1350 Coding: `channel_mode` dtype from `float16` to `float32`
  echopype/utils/coding.py
Labels: bug

#1351 Change float16 to float32 in channel mode test
  echopype/tests/convert/test_convert_ek60.py
Labels: bug

#1331 Add Scalability Options (`use_swap` and chunks) for `ep.calibrate.compute_Sv`
  echopype/calibrate/api.py
  echopype/calibrate/calibrate_base.py
  echopype/echodata/echodata.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/utils/test_processinglevels_integration.py
Labels: bug, enhancement, feature request

#1328 Fix problems in applying `compute_Sv` on combined `EchoData` object
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/env_params.py
  echopype/calibrate/range.py
  echopype/tests/calibrate/test_calibrate.py
  requirements.txt
Labels: bug

#1353 Padding Short Pings
  echopype/convert/parse_base.py
  echopype/tests/convert/test_convert_ek.py
Labels: bug

#1319 Use Echodata `Platform` and `Beam_group1` Variables to Compute Depth for EK60/EK80
  echopype/consolidate/api.py
  echopype/consolidate/ek_depth_utils.py
  echopype/tests/consolidate/test_consolidate_integration.py
Labels: feature request

#1355 docs: Merge data processing level changes from `stable`
  docs/source/processing-levels.md
  docs/source/references.bib
Labels: docs

#1326 Add Index Aggregation Option for Cleaning Mask Functions
  echopype/clean/api.py
  echopype/clean/utils.py
  echopype/tests/clean/test_noise.py
  requirements.txt
Labels: enhancement

#1357 hotfix: Temporarily skip datagrams generated by EC150
  echopype/convert/parse_base.py
  echopype/tests/convert/test_convert_ek80.py
Labels: data conversion

#1323 Added alpha-version code for new AZFP6 format
  echopype/convert/__init__.py
  echopype/convert/api.py
  echopype/convert/parse_azfp6.py
  echopype/convert/set_groups_azfp6.py
  echopype/convert/set_groups_base.py
  echopype/core.py
  echopype/tests/conftest.py
  echopype/tests/convert/test_convert_azfp6.py
  echopype/tests/test_core.py
Labels: data conversion

#1361 Modify dask image in requirement.txt
  requirements.txt
Labels: infrastructure

#1363 Allow Waveform Mode FM in Calibrate API
  echopype/calibrate/api.py
  echopype/tests/calibrate/test_calibrate.py
Labels: feature request

#1359 Use latest MRU parser version; `ep.consolidate.add_location` can be based off Datagram Type
  echopype/consolidate/api.py
  echopype/consolidate/loc_utils.py
  echopype/convert/parse_base.py
  echopype/convert/set_groups_base.py
  echopype/convert/set_groups_ek80.py
  echopype/convert/utils/ek_raw_parsers.py
  echopype/echodata/combine.py
  echopype/echodata/echodata.py
  echopype/echodata/utils_platform.py
  echopype/tests/consolidate/test_add_location.py
  echopype/tests/consolidate/test_consolidate_integration.py
  echopype/tests/convert/test_convert_ek.py
  echopype/tests/convert/test_convert_ek80.py
  echopype/tests/echodata/test_echodata.py
Labels: bug, enhancement, feature request

#1364 `.drop` to `.drop_vars`
  echopype/calibrate/cal_params.py
  echopype/calibrate/calibrate_ek.py
  echopype/calibrate/ecs.py
  echopype/calibrate/range.py
  echopype/echodata/sensor_ep_version_mapping/v05x_to_v06x.py
  echopype/tests/calibrate/test_cal_params.py
  echopype/tests/calibrate/test_cal_params_integration.py
  echopype/tests/echodata/test_echodata.py
  echopype/tests/echodata/test_echodata_version_convert.py
Labels: dependencies
