Repository OSOceanAcoustics/echopype, pull requests merged in 2025-04, with the labels that each got.

#1483 Expand ping time preemptively in `get_vend_cal_params_power`
  echopype/calibrate/cal_params.py
  echopype/tests/calibrate/test_calibrate.py
Labels: bug, enhancement

#1470 Enhance `compute_MVBS` feasability
  echopype/commongrid/api.py
  echopype/commongrid/utils.py
  echopype/tests/commongrid/test_commongrid_api.py
  requirements.txt
Labels: enhancement

#1463 Use normalization to compute echo range scaling
  echopype/consolidate/ek_depth_utils.py
  echopype/tests/consolidate/test_add_depth.py
Labels: bug

#1490 Update data processing docs and contributor guide
  docs/source/_toc.yml
  docs/source/contrib_howto.md
  docs/source/contrib_roadmap.md
  docs/source/contrib_setup.md
  docs/source/contrib_start.md
  docs/source/contributing.md
  docs/source/data-proc-additional.ipynb
  docs/source/data-proc.md
  docs/source/installation.md
  docs/source/processing-levels.md
  docs/source/references.bib
  docs/source/roadmap.md
Labels: docs
