Repository OSOceanAcoustics/echopype, pull requests merged in 2025-02, with the labels that each got.

#1433 Fix tests that fail from new Xarray variable and attribute assignment updates
  echopype/tests/consolidate/test_add_depth.py
Labels: bug

#1436 Assemble AD2CP timestamp with nanosecond precision
  echopype/convert/parse_ad2cp.py
Labels: data conversion

#1434 Use `import_resources.files` instead of the legacy `open_text`
  echopype/convert/set_groups_ad2cp.py
  echopype/echodata/convention/conv.py
Labels: bug

#1437 Add codespell exception
  .pre-commit-config.yaml
  echopype/convert/parse_ad2cp.py
  echopype/convert/set_groups_ad2cp.py
  echopype/convert/set_groups_ek80.py
  echopype/convert/utils/ek_duplicates.py
  echopype/echodata/convention/conv.py
  echopype/tests/consolidate/test_add_depth.py
  echopype/tests/convert/test_convert_ek80.py
  requirements.txt
Labels: infrastructure

#1438 Bump codespell version, add exceptions
  .pre-commit-config.yaml
Labels: infrastructure

#1429 Pin `zarr` and `netcdf4` temporarily [all tests ci]
  echopype/calibrate/ek80_complex.py
  echopype/clean/utils.py
  echopype/testing.py
  echopype/tests/calibrate/test_calibrate.py
  echopype/tests/clean/test_noise.py
  echopype/tests/commongrid/test_commongrid_api.py
  echopype/tests/convert/test_parse_base.py
  requirements.txt
Labels: infrastructure

#1440 Add `type-extensions` to requirements.txt
  requirements.txt
Labels: dependencies

#1442 Add manual trigger to pypi workflow
  .github/workflows/pypi.yaml
Labels: infrastructure

#1443 Update cff citation file
  CITATION.cff
Labels: docs

#1460 Pin scipy to temporarily ensure that rotation matrix calculation does not fail [all tests ci]
  requirements.txt
Labels: bug

#1451 Check if there exist any swap files before cleaning them up [all tests ci]
  echopype/echodata/echodata.py
  echopype/tests/echodata/test_echodata.py
Labels: bug

#1457 Remove `__setattr__` from EchoData [all tests ci]
  echopype/echodata/echodata.py
Labels: infrastructure

#1452 Compute dask array before np array equal [all tests ci]
  echopype/tests/calibrate/test_env_params.py
Labels: bug

#1453 Dataset.dims to Dataset.sizes [all tests ci]
  echopype/consolidate/api.py
  echopype/convert/set_groups_ad2cp.py
  echopype/tests/convert/test_convert_ek80.py
  echopype/tests/echodata/test_echodata_combine.py
Labels: bug

#1454 Chunks as dictionaries in `_get_auto_chunk` [all tests ci]
  echopype/tests/utils/test_coding.py
  echopype/utils/coding.py
Labels: bug

#1462 Set decode timedelta to False since it will default to this in later xarray version [all tests ci]
  echopype/tests/convert/test_convert_ad2cp.py
Labels: bug

#1450 Fix deprecation warning for truth value of an empty array [all tests ci]
  echopype/convert/parse_azfp6.py
Labels: bug

#1458 Fill in NaN for missing EK80 coefficients [all tests ci]
  echopype/calibrate/ek80_complex.py
  echopype/convert/set_groups_ek80.py
  echopype/tests/convert/test_convert_ek80.py
Labels: data conversion

#1447 Backward compatibility of raw-converted dataset with `xr.DataTree` [all tests ci]
  echopype/echodata/echodata.py
  echopype/tests/conftest.py
  echopype/tests/convert/test_convert_ek60.py
  echopype/tests/echodata/test_echodata.py
Labels: bug, AA SI

#1465 Add v0.9.1 and v0.10.0 release notes to docs
  docs/source/whats-new.md
Labels: docs

#1466 Update workflows to use python 3.12 and ubuntu 22.04 [all tests ci]
  .ci_helpers/user_environment.yml
  .github/workflows/docker.yaml
  .github/workflows/packit.yaml
  .github/workflows/pr.yaml
  .github/workflows/pypi.yaml
  .readthedocs.yml
  docs/source/whats-new.md
Labels: infrastructure

#1468 Replace `pkg_resources.resource_string` with `importlib.resources.files` [all tests ci]
  docs/source/whats-new.md
  echopype/echodata/widgets/widgets.py
Labels: dependencies
